
package br.edu.ifpb.pos.client.pessoa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServicePessoaService", targetNamespace = "http://pos.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/pos-soap-server/ServicePessoaService?wsdl")
public class ServicePessoaService
    extends Service
{

    private final static URL SERVICEPESSOASERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEPESSOASERVICE_EXCEPTION;
    private final static QName SERVICEPESSOASERVICE_QNAME = new QName("http://pos.ifpb.edu.br/", "ServicePessoaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pos-soap-server/ServicePessoaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEPESSOASERVICE_WSDL_LOCATION = url;
        SERVICEPESSOASERVICE_EXCEPTION = e;
    }

    public ServicePessoaService() {
        super(__getWsdlLocation(), SERVICEPESSOASERVICE_QNAME);
    }

    public ServicePessoaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServicePessoa
     */
    @WebEndpoint(name = "ServicePessoaPort")
    public ServicePessoa getServicePessoaPort() {
        return super.getPort(new QName("http://pos.ifpb.edu.br/", "ServicePessoaPort"), ServicePessoa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePessoa
     */
    @WebEndpoint(name = "ServicePessoaPort")
    public ServicePessoa getServicePessoaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pos.ifpb.edu.br/", "ServicePessoaPort"), ServicePessoa.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEPESSOASERVICE_EXCEPTION!= null) {
            throw SERVICEPESSOASERVICE_EXCEPTION;
        }
        return SERVICEPESSOASERVICE_WSDL_LOCATION;
    }

}
